### ISSUE TITLE
report-uri

### ISSUE THREAD

**Issue by kravietz** [SpiderOak/django-csp-nonce#12]
Having a static `report-uri` configurable in the `DCN_` configuration variables would be a nice addition to have the `django-csp-nonce` as a standalone CSP handler in a Django app.

**Comment by Bennyoak** [comment]
I feel like this might fall outside the scope of the project.

The idea behind DCN is to offer automated nonce application for an extant policy where there otherwise wouldn't be. DCN's prominant feature is that it stays out of the way of policy decisions. Setting `report-uri` would be better suited in server-side config or something like Django-CSP, IMO.

Also - sorry for the late replies. These two slipped under my radar.

**Comment by Bennyoak** [comment]
Closing this as it is outside the project scope.
